alias nf="neofetch | lolcat"
alias cd..="cd .."
alias cat="bat --theme=TwoDark"
alias findgpu="glxinfo|egrep \"OpenGL vendor|OpenGL renderer\""
alias ls="lsd -la"
alias g++="g++ -std=c++17"
alias spt="spt --config .config/spotify-tui/config.yaml"
