alias nf="neofetch"
alias cd..="cd .."
alias cat="batcat --theme=TwoDark"
alias findgpu="glxinfo|egrep \"OpenGL vendor|OpenGL renderer\""
alias ls="lsd -la"
alias g++="g++ -std=c++17"
alias spt="spt --config ~/snap/spt/current/.config/spotify-tui/config.yaml"
