alias nf="neofetch"
alias cd..="cd .."
alias cat="batcat --theme=TwoDark"
alias respl="powerline-daemon --replace"
alias startMongo="mongod --dbpath /var/lib/mongo --logpath /var/log/mongodb/mongod.log --fork"
alias pip="pip3"
alias findgpu="glxinfo|egrep \"OpenGL vendor|OpenGL renderer\""
alias ls="lsd"
alias g++="g++ -std=c++17"
