alias cd..="cd .."
alias cat="bat --theme=TwoDark"
alias findgpu="glxinfo|egrep \"OpenGL vendor|OpenGL renderer\""
alias g++="g++ -std=c++20"
alias spt="spt --config .config/spotify-tui/config.yaml"
alias restart_plasma="kquitapp5 plasmashell && kstart5 plasmashell &>> /dev/null"
alias start_wayland="XDG_SESSION_TYPE=wayland dbus-run-session startplasma-wayland"
alias kdiff="kitty +kitten diff"
