# Inserts a blank line between shell prompts
add_newline = true
[character]
success_symbol = "[➜](bold green)"
[line_break]
disabled = true
[git_metrics]
# added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false

[status]
disabled = false

